added enemy polling and solved warnings in NoARScene
VR-URFU-Project/ARTowerDefence pull request #21
Opened 2023-05-02 14:11 UTC by AnesVijay

also fixed Orc skirt material

2023-05-12 20:41 UTC, debebantur requested changes
Ты просил - я заревьювил

2023-05-12 20:41 UTC, debebantur commented on Assets/Scripts/ObjectPoolSpawners/EnemySpawner.cs
> +    /// ������ ������ ���������� ����� ������� ������
опять кодировка полетела?

2023-05-12 20:41 UTC, debebantur commented on Assets/Scripts/StartWawe.cs
> +
Закомментированное пока оставим, если всё ок, удалим при рефакторинге

2023-05-12 20:41 UTC, debebantur commented on Assets/Scripts/TowerHealthLogic.cs
> +    new AudioSource audio;
почему new?

2023-05-12 20:41 UTC, debebantur commented on Assets/Scripts/EnemyScript.cs
> +            foreach (Transform child in gameObject.transform)
Может попробовать FindGameObjectWithTag по детям объекта?

2023-05-12 20:41 UTC, debebantur commented on Assets/Scripts/Canon.cs
> +    new AudioSource audio;
new?

2023-05-12 20:41 UTC, debebantur commented on Assets/Materials/EnemiesMat's/Orc skirt.mat
> +  m_Shader: {fileID: 4800000, guid: 933532a4fcc9baf4fa0491de14d08ed7, type: 3}
крутой fileID

2023-05-13 07:52 UTC, AnesVijay commented on Assets/Scripts/StartWawe.cs
> +
так и планировалось

2023-05-13 07:53 UTC, AnesVijay commented on Assets/Scripts/TowerHealthLogic.cs
> +    new AudioSource audio;
Unity "сказал", что так ему лучше)

2023-05-13 07:54 UTC, AnesVijay commented on Assets/Scripts/EnemyScript.cs
> +            foreach (Transform child in gameObject.transform)
FindGameObjectWithTag ищет по всей сцене, что лаконичнее, но не так оптимально

2023-05-13 08:50 UTC, merged